eventpad_htmltopdf_preflight_test:
    path: /test/{fixture}
    defaults: { _controller: EPHtmlToPdfBundle:Preflight:generateFromFixtures }
eventpad_htmltopdf_preflight_index:
    path: /
    defaults: { _controller: EPHtmlToPdfBundle:Preflight:index }
